name: CI CD Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: CI
        uses: actions/setup-node@v3
        with:
          node-version: "16.17"
      - run: cd core && npm run setup && npm run test
      - run: cd web-ui && npm install && npm run build
      - run: echo ${{ secrets.KEY }} | scp -i /dev/stdin -r ./web-ui/build ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/${{ secrets.HOST }}/public
      - name: Deploy Core
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            service nginx reload
            cd ~/deploy/industrial-iot-gateway
            git pull origin main
