name: CI CD Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
      KEY: ${{ secrets.KEY }}
      REACT_APP_BASE_URL: https://94-237-2-157.sg-sin1.upcloud.host:33434
      ORIGIN: http://94-237-2-157.sg-sin1.upcloud.host:443
    steps:
      - uses: actions/checkout@v3
      - name: CI
        uses: actions/setup-node@v3
        with:
          node-version: "16.17"
      - run: cd core && npm run setup && npm run test
      - run: cd web-ui && npm install && npm run build
      - name: Deploy Web ui
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "./web-ui/build/*"
          target: "/var/www/${{ secrets.HOST }}/public/"
          strip_components: 2
      - name: Deploy Core
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            service nginx reload
            cd ~/deploy/industrial-iot-gateway
            git pull origin main
