name: Github Page Deploy Workflow

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16.17"
      - run: cd web-ui && npm install
      - run: cd web-ui && npm run build
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: pages
          build_dir: web-ui/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
